# Generated by Django 3.2.8 on 2023-07-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='subject',
        ),
    ]
