# Generated by Django 3.2.8 on 2023-07-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0003_customuser_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
