# Generated by Django 3.2.8 on 2023-07-16 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0005_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='authenticator.subject'),
        ),
        migrations.AlterField(
            model_name='results',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticator.student'),
        ),
    ]
