# Generated by Django 3.2.8 on 2023-07-17 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0017_alter_customuser_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticator.subject'),
        ),
    ]
