# Generated by Django 3.2.8 on 2023-07-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0019_alter_results_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='grade',
            field=models.CharField(default='F', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='remark',
            field=models.CharField(default='FAIL', max_length=100),
            preserve_default=False,
        ),
    ]
