# Generated by Django 3.2.8 on 2023-07-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0022_alter_results_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avg',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='total_grade',
            field=models.CharField(default='F', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='total_remark',
            field=models.CharField(default='FAIL', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='total_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
