# Generated by Django 3.2.8 on 2023-08-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0023_auto_20230720_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='total_grade',
            field=models.CharField(default='F', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_remark',
            field=models.CharField(default='FAIL', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
