# Generated by Django 3.2.8 on 2023-08-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0025_student_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='qr_code',
            field=models.CharField(max_length=255),
        ),
    ]
