# Generated by Django 3.2.8 on 2023-08-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0026_alter_student_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='qr_code',
            field=models.CharField(default='url', max_length=255),
        ),
    ]
