# Generated by Django 3.2.8 on 2023-08-14 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0027_auto_20230813_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='_class',
            new_name='form',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='class_of',
            new_name='year',
        ),
    ]
