# Generated by Django 3.2.8 on 2023-11-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0030_auto_20231111_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='coordinator_remark',
            field=models.CharField(default='Poor result, you failed. Ensure you work very hard next Semester', max_length=500),
        ),
    ]
